export interface CEDEAR {
  ticker: string
  name: string
  ratio: number
  market: string
}

export const CEDEARS: CEDEAR[] = [
  { ticker: "AAPL", name: "Apple Inc.", ratio: 20, market: "NASDAQ" },
  { ticker: "MSFT", name: "Microsoft Corp.", ratio: 30, market: "NASDAQ" },
  { ticker: "AMZN", name: "Amazon.com Inc.", ratio: 144, market: "NYSE" },
  { ticker: "GOOGL", name: "Alphabet Inc.", ratio: 58, market: "NASDAQ" },
  { ticker: "META", name: "Meta Platforms Inc.", ratio: 24, market: "NASDAQ" },
  { ticker: "NVDA", name: "Nvidia Corporation", ratio: 24, market: "NASDAQ" },
  { ticker: "TSLA", name: "Tesla Inc.", ratio: 12, market: "NASDAQ" },
  { ticker: "AMD", name: "Advanced Micro Devices", ratio: 10, market: "NASDAQ" },
  { ticker: "INTC", name: "Intel Corporation", ratio: 5, market: "NASDAQ" },
  { ticker: "AVGO", name: "Broadcom Inc.", ratio: 39, market: "NASDAQ" },
  { ticker: "ADBE", name: "Adobe Systems Inc.", ratio: 44, market: "NASDAQ" },
  { ticker: "NFLX", name: "Netflix Inc.", ratio: 48, market: "NASDAQ" },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", ratio: 8, market: "NASDAQ" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", ratio: 5, market: "NASDAQ" },
  { ticker: "AMGN", name: "Amgen Inc.", ratio: 30, market: "NASDAQ" },
  { ticker: "QCOM", name: "Qualcomm Inc.", ratio: 10, market: "NASDAQ" },
  { ticker: "TXN", name: "Texas Instruments Inc.", ratio: 5, market: "NASDAQ" },
  { ticker: "COST", name: "Costco Wholesale Corp.", ratio: 48, market: "NASDAQ" },
  { ticker: "BIIB", name: "Biogen Inc.", ratio: 13, market: "NASDAQ" },
  { ticker: "MELI", name: "MercadoLibre Inc.", ratio: 120, market: "NASDAQ" },
  { ticker: "BIDU", name: "Baidu Inc.", ratio: 11, market: "NASDAQ" },
  { ticker: "EBAY", name: "eBay Inc.", ratio: 2, market: "NASDAQ" },
  { ticker: "LRCX", name: "Lam Research Corp.", ratio: 56, market: "NASDAQ" },
  { ticker: "AMAT", name: "Applied Materials Inc.", ratio: 5, market: "NASDAQ" },
  { ticker: "MU", name: "Micron Technology Inc.", ratio: 5, market: "NASDAQ" },
  { ticker: "MRVL", name: "Marvell Technology Inc.", ratio: 14, market: "NASDAQ" },
  { ticker: "ADI", name: "Analog Devices Inc.", ratio: 15, market: "NASDAQ" },
  { ticker: "ISRG", name: "Intuitive Surgical Inc.", ratio: 90, market: "NASDAQ" },
  { ticker: "GILD", name: "Gilead Sciences Inc.", ratio: 4, market: "NASDAQ" },
  { ticker: "ADP", name: "Automatic Data Processing", ratio: 6, market: "NASDAQ" },
  { ticker: "ABNB", name: "Airbnb Inc.", ratio: 15, market: "NASDAQ" },
  { ticker: "MRNA", name: "Moderna Inc.", ratio: 19, market: "NASDAQ" },
  { ticker: "ZM", name: "Zoom Video Communications", ratio: 47, market: "NASDAQ" },
  { ticker: "DOCU", name: "DocuSign Inc.", ratio: 22, market: "NASDAQ" },
  { ticker: "ETSY", name: "Etsy Inc.", ratio: 16, market: "NASDAQ" },
  { ticker: "NTES", name: "NetEase Inc.", ratio: 14, market: "NASDAQ" },
  { ticker: "PANW", name: "Palo Alto Networks Inc.", ratio: 50, market: "NASDAQ" },
  { ticker: "COIN", name: "Coinbase Global Inc.", ratio: 27, market: "NASDAQ" },
  { ticker: "PLTR", name: "Palantir Technologies Inc.", ratio: 3, market: "NYSE" },
  { ticker: "MSTR", name: "MicroStrategy Inc.", ratio: 20, market: "NASDAQ" },
  { ticker: "QQQ", name: "Invesco QQQ Trust (ETF)", ratio: 20, market: "NASDAQ" },
  { ticker: "IBIT", name: "iShares Bitcoin Trust (ETF)", ratio: 10, market: "NASDAQ" },
  { ticker: "ETHA", name: "iShares Ethereum TR ETF", ratio: 5, market: "NASDAQ" },
  { ticker: "IBB", name: "iShares Nasdaq Biotech ETF", ratio: 27, market: "NASDAQ" },
  { ticker: "ARKK", name: "ARK Innovation ETF", ratio: 10, market: "NYSE Arca" },
  { ticker: "ARM", name: "ARM Holdings Plc", ratio: 27, market: "NASDAQ" },
  { ticker: "JPM", name: "JP Morgan Chase & Co.", ratio: 15, market: "NYSE" },
  { ticker: "BAC", name: "Bank of America Corp.", ratio: 4, market: "NYSE" },
  { ticker: "GS", name: "Goldman Sachs Group Inc.", ratio: 20, market: "NYSE" },
  { ticker: "C", name: "Citigroup Inc.", ratio: 3, market: "NYSE" },
  { ticker: "WFC", name: "Wells Fargo & Co.", ratio: 4, market: "NYSE" },
  { ticker: "AXP", name: "American Express Co.", ratio: 15, market: "NYSE" },
  { ticker: "MA", name: "Mastercard Inc.", ratio: 33, market: "NYSE" },
  { ticker: "V", name: "Visa Inc.", ratio: 10, market: "NYSE" },
  { ticker: "SCHW", name: "Charles Schwab Corp.", ratio: 13, market: "NYSE" },
  { ticker: "BK", name: "Bank of New York Mellon", ratio: 2, market: "NYSE" },
  { ticker: "XOM", name: "Exxon Mobil Corporation", ratio: 10, market: "NYSE" },
  { ticker: "CVX", name: "Chevron Corp.", ratio: 16, market: "NYSE" },
  { ticker: "BP", name: "BP PLC", ratio: 5, market: "NYSE" },
  { ticker: "OXY", name: "Occidental Petroleum Corp.", ratio: 5, market: "NYSE" },
  { ticker: "HAL", name: "Halliburton Co.", ratio: 2, market: "NYSE" },
  { ticker: "BKR", name: "Baker Hughes Co.", ratio: 7, market: "NASDAQ" },
  { ticker: "XLE", name: "Energy Select Sector SPDR (ETF)", ratio: 2, market: "NYSE Arca" },
  { ticker: "JNJ", name: "Johnson & Johnson", ratio: 15, market: "NYSE" },
  { ticker: "PFE", name: "Pfizer Inc.", ratio: 4, market: "NYSE" },
  { ticker: "MRK", name: "Merck & Co. Inc.", ratio: 5, market: "NYSE" },
  { ticker: "ABT", name: "Abbott Laboratories", ratio: 4, market: "NYSE" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", ratio: 3, market: "NYSE" },
  { ticker: "LLY", name: "Eli Lilly and Company", ratio: 56, market: "NYSE" },
  { ticker: "NVS", name: "Novartis AG", ratio: 4, market: "NYSE" },
  { ticker: "AZN", name: "AstraZeneca PLC", ratio: 2, market: "NYSE" },
  { ticker: "GSK", name: "GSK PLC", ratio: 4, market: "NYSE" },
  { ticker: "MDT", name: "Medtronic PLC", ratio: 4, market: "NYSE" },
  { ticker: "DHR", name: "Danaher Corp.", ratio: 54, market: "NYSE" },
  { ticker: "ABBV", name: "AbbVie Inc.", ratio: 10, market: "NYSE" },
  { ticker: "GM", name: "General Motors Co.", ratio: 6, market: "NYSE" },
  { ticker: "F", name: "Ford Motor Company", ratio: 1, market: "NYSE" },
  { ticker: "HOG", name: "Harley-Davidson Inc.", ratio: 3, market: "NYSE" },
  { ticker: "HMC", name: "Honda Motor Co. Ltd.", ratio: 1, market: "NYSE" },
  { ticker: "GE", name: "General Electric Co.", ratio: 8, market: "NYSE" },
  { ticker: "HON", name: "Honeywell International", ratio: 8, market: "NYSE" },
  { ticker: "CAT", name: "Caterpillar Inc.", ratio: 20, market: "NYSE" },
  { ticker: "DE", name: "Deere & Co.", ratio: 40, market: "NYSE" },
  { ticker: "MMM", name: "3M Company", ratio: 10, market: "NYSE" },
  { ticker: "LMT", name: "Lockheed Martin Corp.", ratio: 20, market: "NYSE" },
  { ticker: "BA", name: "Boeing Co.", ratio: 6, market: "NYSE" },
  { ticker: "RTX", name: "RTX Corporation", ratio: 5, market: "NYSE" },
  { ticker: "FDX", name: "FedEx Corp.", ratio: 10, market: "NYSE" },
  { ticker: "DAL", name: "Delta Air Lines", ratio: 8, market: "NYSE" },
  { ticker: "AAL", name: "American Airlines Group", ratio: 2, market: "NASDAQ" },
  { ticker: "CCL", name: "Carnival Corporation", ratio: 3, market: "NYSE" },
  { ticker: "LVS", name: "Las Vegas Sands Corp.", ratio: 2, market: "NYSE" },
  { ticker: "WMT", name: "Walmart Inc.", ratio: 5, market: "NYSE" },
  { ticker: "TGT", name: "Target Corp.", ratio: 5, market: "NYSE" },
  { ticker: "MCD", name: "McDonald's Corp.", ratio: 24, market: "NYSE" },
  { ticker: "SBUX", name: "Starbucks Corp.", ratio: 5, market: "NASDAQ" },
  { ticker: "KO", name: "Coca-Cola Co.", ratio: 4, market: "NYSE" },
  { ticker: "PEP", name: "PepsiCo Inc.", ratio: 18, market: "NASDAQ" },
  { ticker: "PM", name: "Philip Morris International", ratio: 4, market: "NYSE" },
  { ticker: "MO", name: "Altria Group Inc.", ratio: 4, market: "NYSE" },
  { ticker: "CL", name: "Colgate-Palmolive Co.", ratio: 3, market: "NYSE" },
  { ticker: "KMB", name: "Kimberly-Clark Corp.", ratio: 6, market: "NYSE" },
  { ticker: "PG", name: "Procter & Gamble Co.", ratio: 6, market: "NYSE" },
  { ticker: "UNH", name: "UnitedHealth Group Inc.", ratio: 20, market: "NYSE" },
  { ticker: "CVS", name: "CVS Health Corp.", ratio: 15, market: "NYSE" },
  { ticker: "IBM", name: "International Business Machines", ratio: 15, market: "NYSE" },
  { ticker: "ORCL", name: "Oracle Corporation", ratio: 3, market: "NYSE" },
  { ticker: "ACN", name: "Accenture PLC", ratio: 75, market: "NYSE" },
  { ticker: "HPQ", name: "HP Inc.", ratio: 1, market: "NYSE" },
  { ticker: "BKNG", name: "Booking Holdings Inc.", ratio: 700, market: "NASDAQ" },
  { ticker: "UBER", name: "Uber Technologies Inc.", ratio: 5, market: "NYSE" },
  { ticker: "SPOT", name: "Spotify Technology S.A.", ratio: 28, market: "NYSE" },
  { ticker: "SQ", name: "Block Inc. (Square)", ratio: 20, market: "NYSE" },
  { ticker: "SNAP", name: "Snap Inc.", ratio: 5, market: "NYSE" },
  { ticker: "TWTR", name: "Twitter / X Corp.", ratio: 5, market: "NYSE" },
  { ticker: "NKLA", name: "Nikola Corporation", ratio: 1, market: "NASDAQ" },
  { ticker: "NIO", name: "NIO Inc.", ratio: 4, market: "NYSE" },
  { ticker: "GOLD", name: "Barrick Gold Corp.", ratio: 2, market: "NYSE" },
  { ticker: "NEM", name: "Newmont Corporation", ratio: 3, market: "NYSE" },
  { ticker: "AEM", name: "Agnico Eagle Mines Ltd.", ratio: 6, market: "NYSE" },
  { ticker: "KGC", name: "Kinross Gold Corp.", ratio: 1, market: "NYSE" },
  { ticker: "GFI", name: "Gold Fields Ltd.", ratio: 1, market: "NYSE" },
  { ticker: "HMY", name: "Harmony Gold Mining", ratio: 1, market: "NYSE" },
  { ticker: "PAAS", name: "Pan American Silver Corp.", ratio: 3, market: "NASDAQ" },
  { ticker: "HL", name: "Hecla Mining Co.", ratio: 1, market: "NYSE" },
  { ticker: "CDE", name: "Coeur Mining Inc.", ratio: 1, market: "NYSE" },
  { ticker: "MUX", name: "McEwen Mining Inc.", ratio: 2, market: "NYSE" },
  { ticker: "NG", name: "NovaGold Resources Inc.", ratio: 1, market: "NYSE" },
  { ticker: "FSLR", name: "First Solar Inc.", ratio: 18, market: "NASDAQ" },
  { ticker: "GLD", name: "SPDR Gold Trust (ETF)", ratio: 50, market: "NYSE" },
  { ticker: "EWZ", name: "iShares MSCI Brazil ETF", ratio: 2, market: "NYSE Arca" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", ratio: 2, market: "NYSE Arca" },
  { ticker: "FXI", name: "iShares China Large-Cap ETF", ratio: 5, market: "NYSE" },
  { ticker: "IVW", name: "iShares S&P 500 Growth ETF", ratio: 20, market: "NYSE Arca" },
  { ticker: "IVE", name: "iShares S&P 500 Value ETF", ratio: 40, market: "NYSE Arca" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", ratio: 10, market: "NYSE Arca" },
  { ticker: "IEUR", name: "iShares Core MSCI Europe ETF", ratio: 11, market: "NYSE Arca" },
  { ticker: "XLF", name: "Financial Select Sector SPDR (ETF)", ratio: 2, market: "NYSE Arca" },
  { ticker: "PBR", name: "Petrobras (ADR)", ratio: 1, market: "NYSE" },
  { ticker: "ITUB", name: "Itaú Unibanco Holding S.A.", ratio: 1, market: "NYSE" },
  { ticker: "BBD", name: "Banco Bradesco S.A.", ratio: 1, market: "NYSE" },
  { ticker: "BSBR", name: "Banco Santander Brasil", ratio: 1, market: "NYSE" },
  { ticker: "ABEV", name: "Ambev S.A.", ratio: 0.33, market: "NASDAQ" },
  { ticker: "BRFS", name: "BRF S.A.", ratio: 0.33, market: "NYSE" },
  { ticker: "ERJ", name: "Embraer S.A.", ratio: 1, market: "NYSE" },
  { ticker: "SID", name: "Companhia Siderúrgica Nacional", ratio: 0.125, market: "NYSE" },
  { ticker: "SBS", name: "Sabesp", ratio: 0.5, market: "NYSE" },
  { ticker: "GGB", name: "Gerdau S.A.", ratio: 0.25, market: "NYSE" },
  { ticker: "ARCO", name: "Arcos Dorados Holdings", ratio: 0.5, market: "NYSE" },
  { ticker: "EBR", name: "Centrais Elétricas Brasileiras (Eletrobras)", ratio: 0.25, market: "NYSE" },
  { ticker: "ELP", name: "COPEL", ratio: 0.33, market: "NYSE" },
  { ticker: "PAGS", name: "PagSeguro Digital Ltd.", ratio: 3, market: "NYSE" },
  { ticker: "DESP", name: "Despegar.com Corp.", ratio: 1, market: "NYSE" },
  { ticker: "LND", name: "BrasilAgro", ratio: 1, market: "NYSE" },
  { ticker: "BAK", name: "Braskem S.A.", ratio: 2, market: "NYSE" },
  { ticker: "NTCO", name: "Natura & Co Holding S.A.", ratio: 1, market: "NYSE" },
  { ticker: "CAAP", name: "Corporación América Airports S.A.", ratio: 0.25, market: "NYSE" },
  { ticker: "BIOX", name: "Bioceres Crop Solutions", ratio: 1, market: "NYSE" },
  { ticker: "GLOB", name: "Globant S.A.", ratio: 18, market: "NYSE" },
  { ticker: "ADGO", name: "Adecoagro S.A.", ratio: 1, market: "NYSE" },
  { ticker: "GPRK", name: "GeoPark Ltd.", ratio: 1, market: "NYSE" },
  { ticker: "LAAC", name: "Lithium Americas (Argentina) Corp.", ratio: 1, market: "NYSE" },
  { ticker: "LAC", name: "Lithium Americas Corp.", ratio: 1, market: "NYSE" },
  { ticker: "BRKB", name: "Berkshire Hathaway Inc. Cl B", ratio: 22, market: "NYSE" },
  { ticker: "BHP", name: "BHP Group Ltd.", ratio: 2, market: "NYSE" },
  { ticker: "RIO", name: "Rio Tinto PLC", ratio: 2, market: "NYSE" },
  { ticker: "VALE", name: "Vale S.A.", ratio: 1, market: "NYSE" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc.", ratio: 2, market: "NYSE" },
  { ticker: "SCCO", name: "Southern Copper Corp.", ratio: 2, market: "NYSE" },
  { ticker: "NUE", name: "Nucor Corp.", ratio: 16, market: "NYSE" },
  { ticker: "DOW", name: "DOW Inc.", ratio: 6, market: "NYSE" },
  { ticker: "DD", name: "DuPont de Nemours Inc.", ratio: 5, market: "NYSE" },
  { ticker: "LYB", name: "LyondellBasell Industries", ratio: 5, market: "NYSE" },
  { ticker: "BAS", name: "BASF SE", ratio: 2, market: "FRANKFURT" },
  { ticker: "BAYN", name: "Bayer AG", ratio: 3, market: "FRANKFURT" },
  { ticker: "ADS", name: "Adidas AG", ratio: 22, market: "XETRA" },
  { ticker: "MBG", name: "Mercedes-Benz Group AG", ratio: 4, market: "FRANKFURT" },
  { ticker: "EOAN", name: "E.ON SE", ratio: 6, market: "FRANKFURT" },
  { ticker: "PHG", name: "Koninklijke Philips N.V.", ratio: 5, market: "NYSE" },
  { ticker: "ING", name: "ING Groep N.V.", ratio: 3, market: "NYSE" },
  { ticker: "AEG", name: "Aegon N.V.", ratio: 1, market: "NYSE" },
  { ticker: "SAN", name: "Banco Santander S.A.", ratio: 0.25, market: "NYSE" },
  { ticker: "BBV", name: "Bilbao Vizcaya Argentaria S.A.", ratio: 1, market: "NYSE" },
  { ticker: "HSBC", name: "HSBC Holdings PLC", ratio: 2, market: "NYSE" },
  { ticker: "BCS", name: "Barclays PLC", ratio: 1, market: "NYSE" },
  { ticker: "LYG", name: "Lloyds Banking Group PLC", ratio: 2, market: "NYSE" },
  { ticker: "NGG", name: "National Grid PLC", ratio: 2, market: "NYSE" },
  { ticker: "DEO", name: "Diageo PLC", ratio: 6, market: "NYSE" },
  { ticker: "EQNR", name: "Equinor ASA", ratio: 6, market: "NYSE" },
  { ticker: "ENI", name: "Eni S.p.A.", ratio: 4, market: "NYSE" },
  { ticker: "TV", name: "Grupo Televisa S.A.", ratio: 3, market: "NYSE" },
  { ticker: "AMX", name: "América Móvil", ratio: 1, market: "NYSE" },
  { ticker: "FMX", name: "Fomento Económico Mexicano (FEMSA)", ratio: 6, market: "NYSE" },
  { ticker: "KOFM", name: "Coca-Cola FEMSA S.A.B.", ratio: 2, market: "NYSE" },
  { ticker: "CX", name: "Cemex S.A.B. de CV", ratio: 1, market: "NYSE" },
  { ticker: "PAC", name: "Grupo Aeroportuario del Pacífico", ratio: 16, market: "NYSE" },
  { ticker: "ASR", name: "Grupo Aeroportuario del Sureste", ratio: 20, market: "NYSE" },
  { ticker: "BABA", name: "Alibaba Group Holding", ratio: 9, market: "NYSE" },
  { ticker: "JD", name: "JD.com Inc.", ratio: 4, market: "NASDAQ" },
  { ticker: "SNP", name: "China Petroleum & Chemical Corp.", ratio: 3, market: "NYSE" },
  { ticker: "LFC", name: "China Life Insurance Co.", ratio: 2, market: "NYSE" },
  { ticker: "KEP", name: "Korea Electric Power Corp.", ratio: 1, market: "NYSE" },
  { ticker: "KB", name: "KB Financial Group Inc.", ratio: 2, market: "NYSE" },
  { ticker: "HDB", name: "HDFC Bank Ltd.", ratio: 2, market: "NYSE" },
  { ticker: "INFY", name: "Infosys Ltd.", ratio: 1, market: "NASDAQ" },
  { ticker: "IBN", name: "ICICI Bank Ltd.", ratio: 1, market: "NYSE" },
  { ticker: "MUFG", name: "Mitsubishi UFJ Financial Group", ratio: 1, market: "NYSE" },
  { ticker: "MFG", name: "Mizuho Financial Group", ratio: 1, market: "NYSE" },
  { ticker: "ERIC", name: "Ericsson", ratio: 2, market: "NASDAQ" },
  { ticker: "NOK", name: "Nokia Corporation", ratio: 1, market: "NYSE" },
  { ticker: "BITF", name: "Bitfarms Ltd.", ratio: 0.2, market: "NASDAQ" },
  { ticker: "HUT", name: "Hut 8 Mining Corp.", ratio: 0.2, market: "NASDAQ" },
  { ticker: "ORLY", name: "O'Reilly Automotive Inc.", ratio: 222, market: "NASDAQ" },
  { ticker: "RACE", name: "Ferrari N.V.", ratio: 83, market: "NYSE" },
  { ticker: "ACNA", name: "Accenture PLC", ratio: 75, market: "NYSE" },
  { ticker: "MMC", name: "Marsh & McLennan Companies", ratio: 16, market: "NYSE" },
  { ticker: "EFX", name: "Equifax Inc.", ratio: 16, market: "NYSE" },
  { ticker: "IFF", name: "International Flavors & Fragrances", ratio: 12, market: "NYSE" },
  { ticker: "MSI", name: "Motorola Solutions Inc.", ratio: 20, market: "NYSE" },
  { ticker: "IP", name: "International Paper Co.", ratio: 4, market: "NYSE" },
  { ticker: "GLW", name: "Corning Inc.", ratio: 4, market: "NYSE" },
  { ticker: "AVY", name: "Avery Dennison Corp.", ratio: 18, market: "NYSE" },
  { ticker: "CAH", name: "Cardinal Health Inc.", ratio: 3, market: "NYSE" },
  { ticker: "SYY", name: "Sysco Corp.", ratio: 2, market: "NYSE" },
  { ticker: "PCAR", name: "PACCAR Inc.", ratio: 3, market: "NASDAQ" },
  { ticker: "HWM", name: "Howmet Aerospace Inc.", ratio: 1, market: "NYSE" },
  { ticker: "NXE", name: "NexGen Energy Ltd.", ratio: 1, market: "NYSE" },
  { ticker: "NU", name: "NU Holdings Ltd.", ratio: 2, market: "NYSE" },
  { ticker: "FNMA", name: "Federal National Mortgage (Fannie Mae)", ratio: 1, market: "OTC" },
  { ticker: "ANF", name: "Abercrombie & Fitch Co.", ratio: 1, market: "NYSE" },
  { ticker: "AUY", name: "Yamana Gold Inc.", ratio: 1, market: "NYSE" },
  { ticker: "CBRD", name: "Companhia Brasileira de Distribuição", ratio: 1, market: "NYSE" },
  { ticker: "CAR", name: "Avis Budget Group Inc.", ratio: 26, market: "NASDAQ" },
  { ticker: "EA", name: "Electronic Arts Inc.", ratio: 14, market: "NASDAQ" },
  { ticker: "AAP", name: "Advance Auto Parts Inc.", ratio: 14, market: "NYSE" },
  { ticker: "BSN", name: "Danone", ratio: 20, market: "FRANKFURT" },
  { ticker: "JMIA", name: "Jumia Technologies AG", ratio: 1, market: "NYSE" },
  { ticker: "AOBA", name: "Aluminum Corp of China", ratio: 1, market: "NYSE" },
  { ticker: "SPY", name: "SPDR S&P 500 ETF", ratio: 50, market: "NYSE Arca" },
  { ticker: "VIST", name: "Vista Energy", ratio: 3, market: "NYSE" },
  { ticker: "UNP", name: "Union Pacific Corp.", ratio: 20, market: "NYSE" },
  { ticker: "GGAL", name: "Grupo Financiero Galicia S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "YPFD", name: "YPF S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "BMA", name: "Banco Macro S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "BBAR", name: "BBVA Argentina S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "SUPV", name: "Supervielle S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "CRES", name: "Cresud S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "ALUA", name: "Aluar Aluminio Argentino S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "TXAR", name: "Ternium Argentina S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "PAMP", name: "Pampa Energia S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "TGSU2", name: "Transportadora de Gas del Sur S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "TGNO4", name: "Transportadora de Gas del Norte S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "CGPA2", name: "Compania General de Combustibles S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "COME", name: "Sociedad Comercial del Plata S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "MIRG", name: "Mirgor S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "MOLI", name: "Molinos Rio de la Plata S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "LOMA", name: "Loma Negra S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "HARG", name: "Holcim Argentina S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "BYMA", name: "Bolsas y Mercados Argentinos S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "CEPU", name: "Central Puerto S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "EDN", name: "Edenor S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "TECO2", name: "Telecom Argentina S.A.", ratio: 1, market: "MERVAL" },
  { ticker: "VALO", name: "Grupo Financiero Valores S.A.", ratio: 1, market: "MERVAL" },
]
